#!/bin/sh


[ -d /dev/net ] ||
    mkdir -p /dev/net
[ -c /dev/net/tun ] ||
    mknod /dev/net/tun c 10 200


iptables -t nat -A POSTROUTING -s 192.168.255.0/24 -o eth0 -j MASQUERADE



echo "openvpn start"
apt-get -qy install openvpn
cd /appli/openvpn/
mkdir /etc/openvpn/jail
openvpn --config /appli/openvpn/server.conf
